CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL
);


CREATE TABLE wallets (
user_id INT PRIMARY KEY,
balance INT DEFAULT 0,
FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE transactions (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
amount INT NOT NULL,
type ENUM('credit','debit') NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP